# Generated by Django 3.1.3 on 2021-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_fname', models.CharField(max_length=100)),
                ('person_lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('subject_of_talk', models.CharField(max_length=1500)),
            ],
        ),
    ]
