# Generated by Django 3.1.3 on 2021-03-31 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vd', '0003_auto_20210330_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_email', models.CharField(max_length=50)),
                ('a_phone', models.IntegerField()),
                ('a_organization', models.CharField(max_length=100)),
                ('event_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vd.upcomingevent')),
            ],
        ),
    ]
